controller:
  replicas: 2

redis:
  enabled: true

server:
  replicas: 2
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: issuer-prod
    tls: true
    hostname: ${hostname}

repoServer:
  replicas: 1

applicationSet:
  replicas: 1

notifications:
  argocdUrl: https://${hostname}

configs:
  secret:
    createSecret: false
  cm:
    url: https://${hostname}
    "resource.exclusions": |
      [ ]
    "oidc.config": |
      name: SSO Login
      issuer: ${issuer}
      clientID: ${client_id}
      clientSecret: ${client_secret}
      requestedScopes: ["openid", "profile", "email", "groups"]
  rbac:
    "policy.csv": |
      g, ArgoCDAdmins, role:admin
      g, ArgoCDViewer, role:readonly
