resources:
  - apiVersion: v1
    kind: Config
    metadata:
      name: loki-s3
      namespace: monitoring
    type: kubernetes.io/basic-auth
    data:
      bucket: ${loki_bucket}

  - apiVersion: v1
    kind: Secret
    metadata:
      name: loki-s3-credentials
      namespace: monitoring
    type: kubernetes.io/basic-auth
    stringData:
      username: ${loki_s3_access_key}
      password: ${loki_s3_secret_key}

  - apiVersion: v1
    kind: Config
    metadata:
      name: tempo-s3
      namespace: monitoring
    type: kubernetes.io/basic-auth
    data:
      bucket: ${tempo_bucket}

  - apiVersion: v1
    kind: Secret
    metadata:
      name: tempo-s3-credentials
      namespace: monitoring
    type: kubernetes.io/basic-auth
    stringData:
      username: ${tempo_s3_access_key}
      password: ${tempo_s3_secret_key}
