controller:
  service:
    loadBalancerIP: ${ip_address}
    externalTrafficPolicy: Local
    annotations:
      cloud.google.com/neg: '{"ingress": true}'
      networking.gke.io/load-balancer-type: "External"

  admissionWebhooks:
    enabled: true

  config:
    use-forwarded-headers: "true"
    use-proxy-protocol: "false"

