global:
  version: "main8935cb277d12a2b9cdffab857f99fefb5b1c09dc"
webhook:
  persistence:
    data:
      size: 1Gi
      storageClass: "wazuh-rwx"
  
  controllers:
    app:
      initContainers:
        permission-fix:
          resources:
            requests:
              cpu: null
              memory: null
            limits:
              cpu: null
              memory: null
      containers:
        app:
          resources:
            requests:
              cpu: null
              memory: null
            limits:
              cpu: null
              memory: null
          
          env:
            SERVER_BASE_URL: 'http://wazuh-cert-server:8000'
            RUST_LOG: 'warn'
            OAUTH_ISSUER: '${openid_connect_url}'
            
            # TODO One of these is required
            OAUTH_CLIENT_ID: ""
            OAUTH_CLIENT_SECRET: ""
            WEBHOOK_BASIC_USER: ""
            WEBHOOK_BASIC_PASSWORD: ""