global:
  domain: "${cert_domain}"
  version: "main02d369668ca611feadd5d094ef4f587501977a3f"
cert:
  controllers:
    main:
      initContainers:
        permission-fix:
          resources:
            requests:
              cpu: null
              memory: null
            limits:
              cpu: null
              memory: null
        ensure-ledger-csv:
          enabled: true # toggle this, as normally the permission-fix should run first
          resources:
            requests:
              cpu: null
              memory: null
            limits:
              cpu: null
              memory: null
      containers:
        main:
          resources:
            requests:
              cpu: null
              memory: null
            limits:
              cpu: null
              memory: null
          
          env:
            RUST_LOG: 'warn'
            OAUTH_ISSUER: '${openid_connect_url}'
  service:
    main:
      annotations:
        cloud.google.com/backend-config: '{"ports":{"http":"cert-backend-config"}}'
      
  persistence:
    data:
      size: 1Gi
      storageClass: "wazuh-rwx"
      
  ingress:
    main:
      enabled: true
      className: null
      annotations:
        networking.gke.io/managed-certificates: "${cert_certificate_name}"
        kubernetes.io/ingress.global-static-ip-name: "${cert_name}"